server:
  port: 8080

spring:
  application:
    name: ms-tipo-cambio
  datasource:
    url: jdbc:h2:mem:db_bank
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

api-tipo-cambio:
  url: https://open.er-api.com/v6/latest
jwt:
  secret: secret